gas optimizations via packing variables
pnslabs/pns-contracts pull request #83
Opened 2023-03-15 13:26 UTC by AmadiMichael

Same as [PR 76](https://github.com/pnslabs/pns-contracts/pull/76) 
Packed struct variables safe gas when they're accessed within the same function call. Reduces number of SSLOADs

The tests pass too

2023-03-15 13:37 UTC, bizmindx requested changes
apart from that LGTM!

2023-03-15 13:38 UTC, bizmindx commented
not sure why the CI  tests aren't executing

2023-03-15 13:45 UTC, AmadiMichael commented on contracts/PNSGuardian.sol
> +
Oh yeah, I added that due to a deploy script that called it but calling `registryContract` still returns the address so I've fixed that now

2023-03-16 02:51 UTC, bizmindx approved these changes
LGTM!

2023-03-16 12:01 UTC, merged